const withUser = {

    products:[{
        id: 10,
        name: 'leche',
        image: '/img/products/1.png',
        price: 69.45,
        brand:'toni' ,
        description:'leche de vaca -Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 101,
    },
    {
        id:11,
        name: 'lechevaca',
        image: '/img/products/2.png',
        price: 9.45,
        brand:'la lechera' ,
        description:'leche de vaca -Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 101,
    },
    {
        id:12,
        name: 'chocolate',
        image: '/img/products/3.png',
        price: 1.15,
        brand:'ferrero roche' ,
        description:'chocolate t consectetur, adipisicing elit. Nulla, quas!',
        categories: 102,
    },
    {
        id:13,
        name: 'manjar',
        image: '/img/products/4.png',
        price: 2.45,
        brand:'inini' ,
        description:'manjar de leche -Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 102,
    },
    {
        id:14,
        name: 'mermelada',
        image: '/img/products/5.png',
        price: 6.01,
        brand:'snob' ,
        description:'mermelada de piña 450g -Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 102,
    },
    {
        id:15,
        name: 'manzana mermelada',
        image: '/img/products/6.png',
        price: 4.45,
        brand:'ades' ,
        description:'mermlada de manzana  amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 102,
    },
    {
        id:16,
        name: 'galleta avena',
        image: '/img/products/7.png',
        price: 0.45,
        brand:'quaker' ,
        description:' galleta de avena  amet consectetur, adipisicing elit Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 102,
    },
    {
        id:17,
        name: 'galleta de sal',
        image: '/img/products/8.png',
        price: 1.00,
        brand:'universal' ,
        description:'galleta pb sal 100g la universal rem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 102,
    },
    {
        id:18,
        name: 'mortadela',
        image: '/img/products/9.png',
        price: 4,
        brand:'italiana' ,
        description:'mortadela la italiana corriente por libra -Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 103,
    },
    {
        id:19,
        name: 'queso',
        image: '/img/products/10.png',
        price: 20.85,
        brand:'kiosko' ,
        description:'queso mozzarella 200g et consectetur, adipisicing elit. Nulla, quas!',
        categories: 101,
    },
    {
        id:20,
        name: 'salchicha',
        image: '/img/products/11.png',
        price: 0.95,
        brand:'italiana' ,
        description:'salchicha de pollola italiana de 20g -Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 103,
    },
    {
        id:21,
        name: 'lenteja',
        image: '/img/products/12.png',
        price: 0.60,
        brand:'' ,
        description:'lenteja en hojuela por libras, adipisicing elit. Nulla, quas!',
        categories: 105,
    },
    {
        id:22,
        name: 'canguil',
        image: '/img/products/13.png',
        price: 0.75,
        brand:'' ,
        description:'canguil en grano por libras -Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 105,
    },
    {
        id:23,
        name: 'arveja',
        image: '/img/products/14.png',
        price: 0.75,
        brand:'' ,
        description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 105,
    },
    {
        id:24,
        name: 'arroz',
        image: '/img/products/15.png',
        price: 0.45,
        brand:'' ,
        description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 105,
    },
    {
        id:25,
        name: 'fideo',
        image: '/img/products/16.png',
        price: 0.60,
        brand:' ' ,
        description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 105,
    },
    {
        id:26,
        name: 'azucar',
        image: '/img/products/17.png',
        price: 0.60,
        brand:' ' ,
        description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 105,
    },
    {
        id:27,
        name: 'sal',
        image: '/img/products/18.png',
        price: 0.60,
        brand:' ' ,
        description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla, quas!',
        categories: 105,
    },
    {
        id:28,
        name: 'jabon',
        image: '/img/products/21.png',
        price: 3.14,
        brand:'azurra' ,
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas earum obcaecati cupiditate blanditiis nihil doloremque quaerat, nostrum aliquid ea culpa?',
        categories: 106,
    },
    {
        id:29,
        name: 'vasos',
        image: '/img/products/19.png',
        price: 2.14,
        brand:'ile' ,
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas earum e blanditiis nihil doloremque quaerat, nostrum aliquid ea culpa?',
        categories: 107,
    },
    {
        id:30,
        name: 'tazas',
        image: '/img/products/20.png',
        price: 3.14,
        brand:'ile' ,
        description:'Lorem r adipisicing elit. Quas earum obcaecati cupiditate blanditiis nihil doloremque quaerat, nostrum aliquid ea culpa?',
        categories: 107,
    },
    {
        id:31,
        name: 'servilletas decoradas',
        image: '/img/products/22.png',
        price: 3.14,
        brand:'familia' ,
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas earum obcaecati cupiditate blanditiis nihil doloremque quaerat, nostrum aliquid ea culpa?',
        categories: 106,
    },
    {
        id:32,
        name: 'servilletas econocmias',
        image: '/img/products/23.png',
        price: 2.14,
        brand:'scott' ,
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas earum obcaecati cupiditate blanditiis nihil doloremque quaerat, nostrum aliquid ea culpa?',
        categories: 106,
    }
]
    
};

export default withUser;